# fly.toml app configuration file generated for delicate-violet-8408 on 2023-10-25T17:39:29+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "delicate-violet-8408"
primary_region = "sin"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
